name: Publish artifacts

on:
  push:

jobs:
  build-gradle-project:
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      USERNAME: shatz.dan@gmail.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew lib:generatePomFileForKotlinMultiplatformPublication
      - name: Publish artifacts
        run: ./gradlew publish